---
# postgresql local agent
# TODO: separate task file
- name: install postgres python deps
  apt: pkg={{ item }} state=latest
  with_items: 
  - libdbd-pg-perl
  - python-psycopg2
  
- name: deploy postgresql local agent conf
  template: src=local-agents/postgresql.conf dest=/usr/lib/observium_agent/local/postgresql.conf owner=root group=root mode=0600  

- name: deploy postgresql local-agent
  template: src=local-agents/postgresql.pl dest=/usr/lib/observium_agent/local/postgresql.pl owner=root group=root mode=0655  

- name: Create a PostgreSQL database user
  postgresql_user: name={{ obs_agent_pg_user }} password={{ obs_agent_pg_pass }} role_attr_flags=CREATEDB state=present
  become: yes
  become_user: postgres
  become_method: sudo
  
- name: create db for observium user
  postgresql_db: name={{ obs_agent_pg_db }} owner={{ obs_agent_pg_user }}
  become: yes
  become_user: postgres
